name: kortebroekaan
description: Kan ik een korte broek aan?

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.18+75

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  language_picker: ^0.4.1
  cupertino_icons: ^1.0.2
  home_widget: ^0.2.0+1
  flutter_spinkit: ^5.1.0
  flutter_dotenv: ^5.0.2
  location:
    git:
      url: https://github.com/781flyingdutchman/flutterlocation.git
      ref: V4
      path: packages/location
  shared_preferences: ^2.0.15
  http: ^0.13.4
  flutter_svg: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.3
  google_mobile_ads: ^3.0.0
  workmanager: ^0.5.0
  firebase_core: ^2.11.0
  firebase_analytics: ^10.3.0
  change_app_package_name: ^1.1.0
  flutter_translate: ^4.0.2
  firebase_database: ^10.1.2
  intl: ^0.18.1
  syncfusion_flutter_charts: ^21.2.3
  share_plus: ^7.0.1
  path_provider: ^2.0.11
  flutter_local_notifications: ^14.0.0+1
  timezone: ^0.9.2
  app_tracking_transparency: ^2.0.2+4
  firebase_crashlytics: ^3.2.0
  flutter_app_name:
    git:
      url: https://github.com/qixotic/flutter_app_name
  flutter_shake_animated: ^0.0.5
  confetti: ^0.7.0
  flutter_vibrate: ^1.3.0
  in_app_purchase: ^3.0.6
  firebase_performance: ^0.9.1+2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/icons/weather/
    - assets/images/
    - assets/icons/
    - assets/
    - .env

flutter_app_name:
  name: "KorteBroekAan"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/yes-man-plain.png"
  image_path_ios: "assets/images/yes-man-ios.png"
