// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhU65-WF85GxfAOCTCTsUSTDa0ezEwuTA',
    appId: '1:11015255472:android:87b2b6a998f6f3c74a9275',
    messagingSenderId: '11015255472',
    projectId: 'korte-broek-aan',
    databaseURL: 'https://korte-broek-aan-default-rtdb.firebaseio.com',
    storageBucket: 'korte-broek-aan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM63iOia0BtGaN_aaAz9r8ckaV0XUYV5A',
    appId: '1:11015255472:ios:3fb54950a92462844a9275',
    messagingSenderId: '11015255472',
    projectId: 'korte-broek-aan',
    databaseURL: 'https://korte-broek-aan-default-rtdb.firebaseio.com',
    storageBucket: 'korte-broek-aan.appspot.com',
    iosClientId: '11015255472-3o3b96v5vu8pqd86fgg2vqcoudlue5af.apps.googleusercontent.com',
    iosBundleId: 'me.kyllian.kortebroekaan.kortebroekaan',
  );
}
